version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamodb-sam-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1eezwo3801g31"
s3_prefix = "dynamodb-sam-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
